补全检查点所需文件
!python run.py --process train --config_path config_kaggle.yml
2024-09-24 06:42:39,729 [MAI VSR:INFO] learner.py:199: Restore from snapshot/ckpt-12
/opt/conda/lib/python3.10/site-packages/keras/src/layers/layer.py:1295: UserWarning: Layer 'mobile_rrn' looks like it has unbuilt state, but Keras is not able to trace the layer call() in order to build it automatically. Possible causes:
1. The call() method of your layer may be crashing. Try to __call__() the layer eagerly on some test input first to see if it works. E.g. x = np.random.random((3, 4)); y = layer(x)
2. If the call() method is correct, then you may need to implement the def build(self, input_shape) method on your layer. It should create all variables used by the layer (e.g. by calling layer.build() on all its children layers).
Exception encountered: '''tensorflow.python.framework.ops.EagerTensor' object has no attribute '_serialize_to_tensors'''
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/keras/src/layers/layer.py:361: UserWarning: build() was called on layer 'mobile_rrn', however the layer does not have a build() method implemented and it looks like it has unbuilt state. This will cause the layer to be marked as built, despite not being actually built, which may cause failures down the line. Make sure to implement a proper build() method.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/keras/src/optimizers/base_optimizer.py:664: UserWarning: Gradients do not exist for variables ['kernel'] when minimizing the loss. If using model.compile(), did you forget to provide a loss argument?
  warnings.warn(